Bug/3 arrumar css da tabela
gckneip/cursorium2 pull request #14
Opened 2024-07-01 14:04 UTC by Antonio-Brum

Table needed to have a fixed size so it fits in the screen without the need of a scroll in the page.
- Size of the table and circuit defined;
- Page scroll disabled;

# How is it now:
![Magi-pr-3-2024-07-01_10 52 49](https://github.com/gckneip/cursorium2/assets/100082116/c2d79c88-092a-4298-aec3-72b9a36cf751)

2024-07-01 14:15 UTC, gckneip requested changes
delete package-lock.json

2024-07-01 14:17 UTC, Antonio-Brum commented
> delete package-lock.json

Bombou

2024-07-01 14:17 UTC, gckneip approved these changes
Bombou

2024-07-10 16:16 UTC, mthsrnn approved these changes

2024-07-27 17:32 UTC, merged